# Generated by Django 5.1.6 on 2025-02-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0004_customuser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
