# Generated by Django 5.1.6 on 2025-02-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctoravailability_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='days_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', help_text='Comma separated days of the week', max_length=255),
            preserve_default=False,
        ),
    ]
