# Generated by Django 5.1.6 on 2025-02-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_doctoravailability_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='days_of_week',
            field=models.ManyToManyField(to='appointments.weekday'),
        ),
    ]
