# Generated by Django 5.1.6 on 2025-02-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_weekday_remove_doctoravailability_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='days_of_week',
            field=models.ManyToManyField(related_name='available_doctors', to='appointments.weekday'),
        ),
    ]
